
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: springcloud-web

  #spring.thymeleaf.encoding=UTF-8
    #spring.thymeleaf.servlet.content-type=text/html
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html